name: widget_recorder_example
description: Demonstrates how to use the widget_recorder package.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  widget_recorder:
    path: ../
  logger: ^1.0.0-nullsafety.0 #null safety
  simple_animations: ^3.1.1
  cached_network_image: ^3.1.0-alpha.1
  hive: ^2.0.0 #null safety
  flutter_svg: ^0.21.0-nullsafety.0 #null safety
  faker: ^2.0.0
  flutter_bloc: ^7.0.0-nullsafety.5 #null safety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/keys/
    - assets/icons/
    - assets/game/icon/
    - images/